[package]
name = "mimic"
version = "0.1.0"
description = "League of Legends settings profiles that follow you across accounts and champions"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "mimic_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset", "tray-icon"] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.13.5", features = ["json"] }
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros", "time", "fs", "signal", "sync"] }
thiserror = "2.0.20"
time = { version = "0.3.55", features = ["serde", "formatting", "parsing", "macros"] }
tokio-tungstenite = { version = "0.30.0", features = ["native-tls"] }
native-tls = "0.2.18"
futures-util = "0.3.34"
base64 = "0.23.1"
tracing = "0.1.44"
tracing-appender = "0.2.5"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
tauri-plugin-clipboard-manager = "2"


# Read the optimization guideline for more details: https://tauri.app/concept/size/#cargo-configuration
[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true

[dev-dependencies]
tempfile = "3.27.0"
windows-sys = { version = "0.61.2", features = ["Win32_Foundation", "Win32_System_Diagnostics_ToolHelp"] }
